-- Create workers table
CREATE TABLE workers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  department TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create vacations table
CREATE TABLE vacations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT REFERENCES workers(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status TEXT DEFAULT 'approved',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Realtime
alter publication supabase_realtime add table workers;
alter publication supabase_realtime add table vacations;

-- Insert default workers (optional, if table is empty)
INSERT INTO workers (name, department) VALUES
  ('Hans Müller', 'Logistik'),
  ('Lisa Schmidt', 'Produktion'),
  ('Peter Weber', 'Logistik'),
  ('Anna Fischer', 'Produktion'),
  ('Klaus Meyer', 'Lager');
